wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1739390177
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      4: 3.6.8
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 2
conv_hidden_channels:
  desc: null
  value: 128
dropout_probability:
  desc: null
  value: 0.2
learning_rate:
  desc: null
  value: 0.001
mlp_hidden_channels:
  desc: null
  value: 256
number_conv_layers:
  desc: null
  value: 3
trial.number:
  desc: null
  value: 0
