version: '3.7'

services:
  clt_localizer:
    container_name: clt_localizer
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - $DATA_FOLDER_EXTERNAL:$DATA_FOLDER
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]