version: '3.8'

services:
  clt_interface:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clt_interface
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    command: npm start
