version: '3.7'

services:
  clt_recognizer:
    container_name: clt_recognizer
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - $DATA_FOLDER_EXTERNAL:$DATA_FOLDER
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]